### ISSUE TITLE
widgettut.md: panic: no wde backend imported

### ISSUE THREAD

**Issue by peterbourgon** [skelterjohn/go.uik#7]
I copy/pasted your widget tutorial code, built it, and tried to run it.

``` bash
peter@sofia:~/src/tmp/gowid$ go get -v .
github.com/skelterjohn/geom (download)
github.com/skelterjohn/go.uik (download)
code.google.com/p/draw2d (download)
code.google.com/p/freetype-go (download)
github.com/skelterjohn/go.wde (download)
github.com/skelterjohn/geom
image/draw
code.google.com/p/freetype-go/freetype/truetype
code.google.com/p/freetype-go/freetype/raster
github.com/skelterjohn/go.wde
code.google.com/p/freetype-go/freetype
code.google.com/p/draw2d/draw2d
github.com/skelterjohn/go.uik
github.com/skelterjohn/go.uik/layouts
github.com/skelterjohn/go.uik/widgets
tmp/gowid
peter@sofia:~/src/tmp/gowid$ gowid
panic: no wde backend imported

goroutine 1 [running]:
github.com/skelterjohn/go%2ewde._func_001()
    /Users/peter/src/github.com/skelterjohn/go.wde/wde.go:81 +0x47
github.com/skelterjohn/go%2ewde.Run()
    /Users/peter/src/github.com/skelterjohn/go.wde/wde.go:77 +0x1d
main.main()
    /Users/peter/src/tmp/gowid/x.go:15 +0x26
 . . .
```

Am I missing something?

**Comment by skelterjohn** [comment]
You need to import a WDE backend. See go.uik/uiktest for an example.

I didn't want to specify the backend in the tutorial, because then it
wouldn't be cross-platform.

On Thu, May 17, 2012 at 6:44 PM, Peter Bourgon <
reply@reply.github.com

**Comment by peterbourgon** [comment]
Aha. Sorry for the noise.
